Start testing: Apr 11 12:50 EDT
----------------------------------------------------------
1/1 Testing: qa_serialsource_b
1/1 Test: qa_serialsource_b
Command: "/bin/sh" "/home/josh/Documents/SD/21-29-Starobike/GNU/NewModule/gr-seniordesign/build/python/qa_serialsource_b_test.sh"
Directory: /home/josh/Documents/SD/21-29-Starobike/GNU/NewModule/gr-seniordesign/build/python
"qa_serialsource_b" start time: Apr 11 12:50 EDT
Output:
----------------------------------------------------------
E
======================================================================
ERROR: test_001_t (__main__.qa_serialsource_b)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/josh/.local/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/josh/Documents/SD/21-29-Starobike/GNU/NewModule/gr-seniordesign/python/qa_serialsource_b.py", line 37, in test_001_t
    src = serialsource_b().work(None,out)
  File "/home/josh/Documents/SD/21-29-Starobike/GNU/NewModule/gr-seniordesign/python/serialsource_b.py", line 41, in work
    ser = serial.Serial(arduino_port, baud)
  File "/home/josh/.local/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/josh/.local/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
<end of output>
Test time =   0.35 sec
----------------------------------------------------------
Test Failed.
"qa_serialsource_b" end time: Apr 11 12:50 EDT
"qa_serialsource_b" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Apr 11 12:50 EDT
